version: "3"

volumes:
   db:
      driver: local

services:
   mysqldb:
      image: mariadb
      restart: unless-stopped
      container_name: piggy-bank-db
      env_file: ./.env
      environment:
         - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
         - MYSQL_USER=$DB_USER
         - MYSQL_PASSWORD=$DB_PASSWORD
         - MYSQL_DATABASE=$DB_DATABASE
      volumes:
         - db:/var/lib/mysql
      ports:
         - 3306:3306
   piggy-bank-server:
      container_name: piggy-bank-server
      build: ./
      image: piggy-bank-server/latest
      depends_on:
         - mysqldb
      env_file: ./.env
      environment:
         - DB_HOST=piggy-bank-db
         - DB_DATABASE=$DB_DATABASE
         - DB_USER=$DB_USER
         - DB_PASSWORD=$DB_PASSWORD
         - NODE_ENV=$NODE_ENV
         - HOST=$HOST
         - PORT=$PORT
         - JWT_TOKEN=$JWT_TOKEN
      restart: unless-stopped
      ports:
         - $DOCKER_PORT:$PORT
      volumes:
         - ./:/piggy-bank-server
         - /piggy-bank-server/node_modules
